apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc1-depl
  namespace: student
  labels:
    app: sv2
    mntr: a0z9-at-rambler
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: sv2
  template:
    metadata:
      labels:
        app: sv2    
    spec:
      containers:
        - name: bbox
          image: busybox
          ports: 
            - containerPort: 22
          command:
            - bin/sh
            - -c
            - |
              echo Test bbox start, $HOSTNAME
              RAN=$(($RANDOM % 10))
              sleep $RAN
              echo "$HOSTNAME ($RAN)  `date`" >> /mydata/data
              RAN=$(($RANDOM % 10))
              sleep $RAN
              echo "$HOSTNAME ($RAN)  `date`" >> /mydata/data

              ping 8.8.8.8 &
              sleep 5
              kill %1
              echo Test bbox finished, $HOSTNAME
              echo Listen 22 port, 100m ...
              nc -l -p 22 &
              sleep 6000
              kill %1
              
          volumeMounts:
          - name: vol1
            mountPath: /mydata
  #    restartPolicy: OnFailure
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc-20m

