apiVersion: batch/v1
kind: Job
metadata:
  name: greets2
  namespace: student

spec:
  backoffLimit: 3
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
        - name: greets
          image: busybox
          command: 
           - /bin/sh
           - -c
           - |
             echo Hello, Andrei! Start job... 
             sleep 15 
             echo ..its done, by!
             exit 0

      restartPolicy: Never    
