apiVersion: v1
kind: Pod

metadata:
        name: bbox-private-loads

spec:
        containers:
        - name: bbox-loads
          image: dock01:5002/busy:5
          command: ["dd"]
          args: ["if=/dev/zero","of=/dev/null","bs=4096"]
          resources:
                  limits:
                          cpu: "250m"
                          memory: 30Mi

        imagePullSecrets:
        - name: secret1
          
