apiVersion: v1
kind: Pod

metadata:
        name: bbox-private

spec:
        containers:
        - name: bbox-private-container
          image: dock01:5002/busy:5
          command: ["ping"]
          args: ["8.8.8.8"]

        imagePullSecrets:
        - name: secret1
          
