kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-cr-bind
    namespace: training
subjects:

        - kind: ServiceAccount
          name: readers
          namespace: training
roleRef:
          kind: ClusterRole
          name: readers-cr
          apiGroup: 'rbac.authorization.k8s.io'         

