kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-cr
    namespace: training
    #  labels:

rules:
  - apiGroups: [""]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["apps"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["extensions"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["batch"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 




