kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-limited1
    namespace: student
    #  labels:

rules:
  - apiGroups: [""]
    resources: ["namespaces","pods","pods/log","nodes","services","deployments"]
    verbs: ["get","list","watch"] 
  
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch"] 

