# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrMDE6NTAwMiI6IHsKCQkJImF1dGgiOiAiYzNSMVpHVnVkRHB3WVhOeiIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: "2022-12-09T13:11:46Z"
  name: dock5002
  namespace: default
  resourceVersion: "130207"
  uid: e97b2be2-3495-4e6a-bdd1-6c70c77def58
type: kubernetes.io/dockerconfigjson
