apiVersion: v1
kind: Service
metadata:
  name: stada-svc 
  namespace: stada
  labels:
    k8s-app: wapp5-form

spec:
  type: NodePort      
  clusterIP: 10.105.155.5
  clusterIPs:
    - 10.105.155.5
  selector:
    k8s-app: wapp5-form
  ports:
    - targetPort: 8080
      port: 8075
      nodePort: 30155

