apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wapp5-1
  name: wapp5-1
  namespace: default
spec:
  ports:
  - nodePort: 31133
    port: 8099
    targetPort: 8080
  selector:
    k8s-app: wapp5-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
