apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pvc-nfs
  namespace: student

spec:
  accessModes:
  - ReadWriteMany
  volumeName: pv-nfs

  resources:
     requests:
       storage: 300Mi
